server:
  port: 8184

spring:
  application:
    name: USERS-APP
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  profiles:
    active: docker
  
  thymeleaf:
    check-template-location: false