spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-APP
          uri: lb://AUTH-APP  
          predicates:
            - Path=/auth/**  
        - id: LOCATIONS-APP
          uri: lb://LOCATIONS-APP  
          predicates:
            - Path=/locations/**  
        - id: REQUESTS-APP
          uri: lb://REQUESTS-APP  
          predicates:
            - Path=/requests/**  
        - id: USERS-APP
          uri: lb://USERS-APP  
          predicates:
            - Path=/users/**  
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-app:8761/eureka/
  instance:
    preferIpAddress: false
