server:
  port: 8181

spring:
  profiles:
    active: docker  
  application:
    name: auth-app
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    check-template-location: false
